apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexadesk
  namespace: nexadesk-staging
  labels:
    app.kubernetes.io/name: nexadesk
    app.kubernetes.io/environment: staging
  annotations:
    # Ajuste se seu controller usar outra classe (ex.: traefik)
    kubernetes.io/ingress.class: nginx

    # Permite path /api funcionar sem problemas
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: staging.nexadesk.local
      http:
        paths:
          # API
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: nexadesk-api
                port:
                  number: 80

          # Frontend (SPA)
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: nexadesk-frontend
                port:
                  number: 80
